# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

resources:
  pipelines:
  - pipeline: tech-arti-blogs.pipelines-dotnet-core     # Name of the pipeline resource
    source: tech-arti-blogs.Trigger-Pipeline-From-Another-Pipeline # Name of the pipeline referenced by the pipeline resource
    project: Configuring Pipeline # Required only if the source pipeline is in another project
    trigger: true # enable the trigger

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
